<br /><br />
<div class='row padding20 text-white'>
	<?php
    	echo"<div class='col-lg-10 offset-lg-1 padding0'>";
			echo"<nav aria-label='breadcrumb'>";
  				echo"<ol class='breadcrumb'>";
    				echo"<li class='breadcrumb-item'><a href='".$url."regras'>Regras</a></li>";
    				echo "<li class='breadcrumb-item active' aria-current='page'>Detalhes</li>";
    			echo "</ol>";
			echo"</nav>";
		echo "</div>";
    ?>
	<?php
		echo "<div class='col-lg-10 offset-lg-1 background_dark'>";
			echo"<a href='javascript:window.history.go(-1)' class='link padding' title='Voltar'>";
				echo"<span class='glyphicon glyphicon-arrow-left text-white' style='font-size: 25px;'></span>";
			echo"</a>";
			echo "<br />";
			echo "<br />";
			echo "<div class='table-responsive'>";
				echo "<table class='table table-striped table-hover text-white'>";
					echo"</tr>";
					echo "<tr>";
						echo "<td>Modalidade</td>";
						echo "<td>".$obj['Nome_modalidade']."</td>";
					echo"</tr>";
					echo "<tr>";
						echo "<td>Data de registro</td>";
						echo "<td>".$obj['Data_registro']."</td>";
					echo"</tr>";
					echo"<tr>";
						echo "<td>Período letivo</td>";
						echo "<td>".$obj['Periodo']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Avaliar faltas por disciplina</td>";
						echo "<td>".(($obj['Avaliar_faltas'] == 1) ? 'Sim' : 'Não')."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Limite de faltas</td>";
						echo "<td>".$obj['Limite_falta']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Dias letivos</td>";
						echo "<td>".$obj['Dias_letivos']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Média</td>";
						echo "<td>".$obj['Media']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Duração da aula</td>";
						echo "<td>".$obj['Duracao_aula']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Hora de início da aula</td>";
						echo "<td>".$obj['Hora_inicio_aula']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Quantidade de aulas por dia</td>";
						echo "<td>".$obj['Quantidade_aula']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Reprovas</td>";
						echo "<td>".$obj['Reprovas']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Quantidade mínima de alunos</td>";
						echo "<td>".$obj['Qtd_minima_aluno']."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>Quantidade máxima de alunos</td>";
						echo "<td>".$obj['Qtd_maxima_aluno']."</td>";
					echo "</tr>";
					echo"<tr>";
						echo "<td>Ativo</td>";
						echo "<td>".(($obj['Ativo'] == 1) ? 'Sim' : 'Não')."</td>";
					echo "</tr>";
				echo "<tr>";
						echo "<td colspan='2' class='text-center'>Intervalos</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td colspan='2'>";
							echo "<div class='intervalos' style='height: 250px; max-height: 250px;'>";
							echo "<table class='table table-striped table-hover'>";
								echo "<thead>";
									echo "<tr>";
										echo "<td>Dia</td>";
										echo "<td>Hora início</td>";
										echo "<td>Hora fim</td>";
									echo "</tr>";
								echo "</thead>";
								echo "<tbody>";
									for($i = 0; $i < count($intervalos); $i++)
									{
										echo "<tr>";
											echo "<td>";
												echo $intervalos[$i]['Dia'];
											echo "</td>";
											echo "<td>";
												echo $intervalos[$i]['Hora_inicio'];
											echo "</td>";
											echo"<td>";
												echo $intervalos[$i]['Hora_fim'];
											echo "</td>";
										echo "</tr>";
									}
								echo "</tbody>";
							echo "</table>";
							echo "</div>";
						echo"</td>";
					echo "</tr>";
					echo"<tr>";
						echo "<td colspan='2' class='text-center'>Etapas</td>";
					echo "</tr>";
					echo"<tr>";
						echo "<td colspan='2'>";
							echo "<div class='etapas' style='height: 250px; max-height: 250px;'>";
								echo "<table class='table table-striped table-hover'>";
									echo "<thead>";
										echo "<tr>";
											echo "<td>Nome</td>";
											echo "<td>Valor</td>";
											echo "<td title='Data em que começa o bimestre durante o ano'>Data de início</td>";
											echo "<td title='Data em que termina o bimestre durante o ano'>Data de fim</td>";
											echo "<td title='Data em que começa a ser permitido a inserção de notas no portal pelos professores (opcional)'>Data de abertura</td>";
											echo "<td title='Data em que termina a permissão de inserção de notas no portal pelos professores (opcional)'>Data de fechamento</td>";
										echo "</tr>";
									echo "</thead>";
									echo "<tbody>";
										for($i = 0; $i < count($etapas); $i++)
										{
											echo "<tr>";
												echo"<td>";
													echo $etapas[$i]['Nome'];
												echo "</td>";
												echo "<td>";
													echo $etapas[$i]['Valor'];
												echo "</td>";
												echo "<td>";
													echo $etapas[$i]['Data_inicio'];
												echo "</td>";
												echo "<td>";
													echo $etapas[$i]['Data_fim'];
												echo "</td>";
												echo "<td>";
													echo (($etapas[$i]['Data_abertura'] == '00/00/0000') ? '' : $etapas[$i]['Data_abertura']);
												echo "</td>";
												echo "<td>";
													echo (($etapas[$i]['Data_fechamento'] == '00/00/0000') ? '' : $etapas[$i]['Data_fechamento']);
												echo "</td>";
											echo "</tr>";
										}
									echo "</tbody>";
								echo "</table>";
							echo "</div>";
						echo "</td>";
					echo "</tr>";
					echo"<tr>";
						echo "<td colspan='2' class='text-center'>Etapas extras</td>";
					echo "</tr>";
					echo"<tr>";
						echo "<td colspan='2'>";
							echo "<div class='etapas' style='height: 250px; max-height: 250px;'>";
								echo "<table class='table table-striped table-hover'>";
									echo "<thead>";
										echo "<tr>";
											echo "<td>Nome</td>";
											echo "<td>Valor</td>";
											echo "<td>Média</td>";
											echo "<td title='Data em que começa a ser permitido a inserção de notas no portal pelos professores (opcional)'>Data de abertura</td>";
											echo "<td title='Data em que termina a permissão de inserção de notas no portal pelos professores (opcional)'>Data de fechamento</td>";
										echo "</tr>";
									echo "</thead>";
									echo "<tbody>";
										for($i = 0; $i < count($etapas_extras); $i++)
										{
											echo "<tr>";
												echo"<td>";
													echo $etapas_extras[$i]['Nome'];
												echo "</td>";
												echo "<td>";
													echo $etapas_extras[$i]['Valor'];
												echo "</td>";
												echo "<td>";
													echo $etapas_extras[$i]['Media'];
												echo "</td>";
												echo "<td>";
													echo (($etapas_extras[$i]['Data_abertura'] == '00/00/0000') ? '' : $etapas_extras[$i]['Data_abertura']);
												echo "</td>";
												echo "<td>";
													echo (($etapas_extras[$i]['Data_fechamento'] == '00/00/0000') ? '' : $etapas_extras[$i]['Data_fechamento']);
												echo "</td>";
											echo "</tr>";
										}
									echo "</tbody>";
								echo "</table>";
							echo "</div>";
						echo "</td>";
					echo "</tr>";
				echo "</table>";
			echo "</div>";
		echo "</div>";
	?>
</div>